# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kk/CLionProjects/oop/final

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kk/CLionProjects/oop/final

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kk/CLionProjects/oop/final/CMakeFiles /home/kk/CLionProjects/oop/final/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kk/CLionProjects/oop/final/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named final

# Build rule for target.
final: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 final
.PHONY : final

# fast build rule for target.
final/fast:
	$(MAKE) -f CMakeFiles/final.dir/build.make CMakeFiles/final.dir/build
.PHONY : final/fast

MemoryPool.o: MemoryPool.cpp.o

.PHONY : MemoryPool.o

# target to build an object file
MemoryPool.cpp.o:
	$(MAKE) -f CMakeFiles/final.dir/build.make CMakeFiles/final.dir/MemoryPool.cpp.o
.PHONY : MemoryPool.cpp.o

MemoryPool.i: MemoryPool.cpp.i

.PHONY : MemoryPool.i

# target to preprocess a source file
MemoryPool.cpp.i:
	$(MAKE) -f CMakeFiles/final.dir/build.make CMakeFiles/final.dir/MemoryPool.cpp.i
.PHONY : MemoryPool.cpp.i

MemoryPool.s: MemoryPool.cpp.s

.PHONY : MemoryPool.s

# target to generate assembly for a file
MemoryPool.cpp.s:
	$(MAKE) -f CMakeFiles/final.dir/build.make CMakeFiles/final.dir/MemoryPool.cpp.s
.PHONY : MemoryPool.cpp.s

STL_allocator.o: STL_allocator.cpp.o

.PHONY : STL_allocator.o

# target to build an object file
STL_allocator.cpp.o:
	$(MAKE) -f CMakeFiles/final.dir/build.make CMakeFiles/final.dir/STL_allocator.cpp.o
.PHONY : STL_allocator.cpp.o

STL_allocator.i: STL_allocator.cpp.i

.PHONY : STL_allocator.i

# target to preprocess a source file
STL_allocator.cpp.i:
	$(MAKE) -f CMakeFiles/final.dir/build.make CMakeFiles/final.dir/STL_allocator.cpp.i
.PHONY : STL_allocator.cpp.i

STL_allocator.s: STL_allocator.cpp.s

.PHONY : STL_allocator.s

# target to generate assembly for a file
STL_allocator.cpp.s:
	$(MAKE) -f CMakeFiles/final.dir/build.make CMakeFiles/final.dir/STL_allocator.cpp.s
.PHONY : STL_allocator.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/final.dir/build.make CMakeFiles/final.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/final.dir/build.make CMakeFiles/final.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/final.dir/build.make CMakeFiles/final.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... final"
	@echo "... edit_cache"
	@echo "... MemoryPool.o"
	@echo "... MemoryPool.i"
	@echo "... MemoryPool.s"
	@echo "... STL_allocator.o"
	@echo "... STL_allocator.i"
	@echo "... STL_allocator.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

